### ISSUE TITLE
Modal date input 컴포넌트

### ISSUE THREAD

**Issue by Jyophie** [SWCF-8TEAM/taskify#31]
## 📝 DESCRIBE
#29 해당 모달 인풋(date type) 문제인데요.

- react date picker 적용한 상태에서 위치 문제는 해결 했습니다. (DatePickerWrapper로 위치 조정)
- 아이콘을 저희 asset - calendar.svg 로 적용했습니다.
- 다만 하기 TODO에 적은 이슈들이 해결이 안되네요 🥲 
- 그리고 좀 코드가 더러워서... 리팩토링이 필요합니다...

현 상태
<img width="720" alt="Screenshot 2023-12-21 at 14 08 04" src="https://github.com/SWCF-8TEAM/taskify/assets/133554119/21c61469-6749-466a-8800-4428c0839ac7">

## ✅ TODO

- [x] 캘린더 아이콘 사이즈 및 위치를 날짜 텍스트와 align 하게 조정 필요
- [x] placeholder 적용 안됨 이슈 해결 필요
- [x] focus 상태일때 아이콘 fill 색상 변경 반영 안됨 이슈 해결 필요

**Comment by Jyophie** [comment]
#65 라이브러리 교체하고 해결했습니다. 물론 캘린더 아이콘 위치는 기획안 대로 되지 않으나, 최대한 비슷하게 구현했습니다! 흑흑 드디어 해결...
